### ISSUE TITLE
Jira issue transition is not working

### ISSUE THREAD

**Issue by dark-vex** [ansible-collections/community.general#818]
##### SUMMARY
When trying to change the issue transition from _Open_ to _In Progress_ this fail with the message **_Failed find valid transition for 'In Progress'_**
I have also installed from ansible-galaxy the community.general collection 1.1.0 which should contain a fix for a similar issue (see issue #109 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

modules/web_infrastructure/jira.py
community.general/plugins/modules/web_infrastructure/jira.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
root@WSL:~# ansible-config dump --only-changed
root@WSL:~#        
```

##### OS / ENVIRONMENT

Debian 10.5 on WSL2

##### STEPS TO REPRODUCE

Just trying to change the assignee and status to "In Progress" using Jira Cloud (with a default workflow)

```yaml
---
- name: Test Read/Write Jira
  hosts: localhost
  pre_tasks:
    - name: Assign an issue and change status
      jira:
        uri: https://<my-workspace>.atlassian.net/
        username: '{{ user }}'
        password: '{{ passw }}'
        issue: '{{ issue_id }}'
        operation: transition
        assignee: ansibleaut
        status: In Progress
```

##### EXPECTED RESULTS

I'm expecting to see the issue assigned and his state changed from _Open_ to _In Progress_

##### ACTUAL RESULTS

```paste below
TASK [Assign an issue and change status] ***************************************************************************************************************************
task path: /root/jira.yaml:11
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1598184579.12-6361-229671283047844 `" && echo ansible-tmp-1598184579.12-6361-229671283047844="` echo /root/.ansible/tmp/ansible-tmp-1598184579.12-6361-229671283047844 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/web_infrastructure/jira.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-6285hPq_Do/tmpW7rYUv TO /root/.ansible/tmp/ansible-tmp-1598184579.12-6361-229671283047844/AnsiballZ_jira.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1598184579.12-6361-229671283047844/ /root/.ansible/tmp/ansible-tmp-1598184579.12-6361-229671283047844/AnsiballZ_jira.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1598184579.12-6361-229671283047844/AnsiballZ_jira.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1598184579.12-6361-229671283047844/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_jira_payload_9XKThG/ansible_jira_payload.zip/ansible/modules/web_infrastructure/jira.py", line 440, in main
  File "/tmp/ansible_jira_payload_9XKThG/ansible_jira_payload.zip/ansible/modules/web_infrastructure/jira.py", line 348, in transition
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "assignee": "ansibleaut",
            "comment": null,
            "description": null,
            "fields": {
                "assignee": {
                    "name": "ansibleaut"
                },
            },
            "inwardissue": null,
            "issue": "AUT-15",
            "issuetype": null,
            "linktype": null,
            "operation": "transition",
            "outwardissue": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "project": null,
            "status": "In Progress",
            "summary": null,
            "timeout": 10.0,
            "uri": "https://<my-workspace>.atlassian.net",
            "username": <my-username>",
            "validate_certs": true
        }
    },
    "msg": "Failed find valid transition for 'In Progress'"
}
```

This is what is returning curl _/rest/api/latest/issue/AUT-15/transitions_ API call
```
{
  "expand": "transitions",
  "transitions": [
    {
      "id": "11",
      "name": "Start Progress",
      "to": {
        "self": "https://<my-workspace>.atlassian.net/rest/api/2/status/3",
        "description": "This issue is being actively worked on at the moment by the assignee.",
        "iconUrl": "https://<my-workspace>.atlassian.net/images/icons/statuses/inprogress.png",
        "name": "In Progress",
        "id": "3",
        "statusCategory": {
          "self": "https://<my-workspace>.atlassian.net/rest/api/2/statuscategory/4",
          "id": 4,
          "key": "indeterminate",
          "colorName": "yellow",
          "name": "In Progress"
        }
      },
      "hasScreen": false,
      "isGlobal": false,
      "isInitial": false,
      "isAvailable": true,
      "isConditional": false
    }
  ]
}
```

**Comment by Dark-Vex** [comment]
@felixfontein thanks, I have tried right now with `community.general.jira` but I still get the same error

```
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1598201214.79-200-25904839986424 `" && echo ansible-tmp-1598201214.79-200-25904839986424="` echo /root/.ansible/tmp/ansible-tmp-1598201214.79-200-25904839986424 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/community/general/plugins/modules/jira.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-1240Ph6Je/tmp1N2eaj TO /root/.ansible/tmp/ansible-tmp-1598201214.79-200-25904839986424/AnsiballZ_jira.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1598201214.79-200-25904839986424/ /root/.ansible/tmp/ansible-tmp-1598201214.79-200-25904839986424/AnsiballZ_jira.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1598201214.79-200-25904839986424/AnsiballZ_jira.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1598201214.79-200-25904839986424/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_community.general.jira_payload_wmaw5h/ansible_community.general.jira_payload.zip/ansible_collections/community/general/plugins/modules/jira.py", line 529, in main
  File "/tmp/ansible_community.general.jira_payload_wmaw5h/ansible_community.general.jira_payload.zip/ansible_collections/community/general/plugins/modules/jira.py", line 433, in transition
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "assignee": "ansibleaut",
            "comment": null,
            "description": null,
            "fields": {
                "assignee": {
                    "name": "ansibleaut"
                },
            },
            "inwardissue": null,
            "issue": "AUT-15",
            "issuetype": null,
            "jql": null,
            "linktype": null,
            "maxresults": null,
            "operation": "transition",
            "outwardissue": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "project": null,
            "status": "In Progress",
            "summary": null,
            "timeout": 10.0,
            "uri": "https://<my-workspace>.atlassian.net",
            "username": <my-username>",
            "validate_certs": true
        }
    },
    "msg": "Failed find valid transition for 'In Progress'"
}
```

**Comment by Akasurde** [comment]
@dark-vex I am not able to reproduce this error.

```
    - name: Transit an issue
      community.general.jira:
        uri: '{{ jirauri }}'
        username: '{{ jira_username }}'
        password: '{{ jira_api_token }}'
        project: scrum-project
        operation: transition
        issue: "SP-1"
        status: "In Progress"
```

```
TASK [Transit an issue] ***********************************************************************
changed: [localhost] => {"changed": true, "meta": {}}
```

Can you please check if you have the correct transition states or you are not using some other locale?

<img width="1243" alt="Screenshot 2021-01-07 at 16 01 04" src="https://user-images.githubusercontent.com/633765/103882309-9c0f5600-5101-11eb-9022-dcdcd2066c6b.png">

**Comment by Akasurde** [comment]
```
{
  "hasScreen": False,
  "id": "21",
  "isAvailable": True,
  "isConditional": False,
  "isGlobal": True,
  "isInitial": False,
  "isLooped": False,
  "name": "In Progress", # <----------------- This 
  "to": {
    "description": "This issue is being actively worked on at the moment by the assignee.",
    "iconUrl": "https://ansible-test.atlassian.net/images/icons/statuses/inprogress.png",
    "id": "3",
    "name": "In Progress", # <---------------------- This
    "self": "https://ansible-test.atlassian.net/rest/api/2/status/3",
    "statusCategory": {
      "colorName": "yellow",
      "id": 4,
      "key": "indeterminate",
      "name": "In Progress",
      "self": "https://ansible-test.atlassian.net/rest/api/2/statuscategory/4"
    }
  }
}
```
My transition status name is `In Progress` whereas yours is `"name": "Start Progress",`.

Can you try changing `status` and re-run?

**Comment by dark-vex** [comment]
@Akasurde damn! you're right I've changed it to "Start Progress" and it worked, apologies, I was pretty sure to have tried also with it!

```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "assignee": null,
            "comment": null,
            "description": null,
            "fields": {},
            "inwardissue": null,
            "issue": "AUT-29",
            "issuetype": null,
            "jql": null,
            "linktype": null,
            "maxresults": null,
            "operation": "transition",
            "outwardissue": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "project": "AUT",
            "status": "Start Progress",
            "summary": null,
            "timeout": 10.0,
            "uri": "https://<my-jira>.atlassian.net",
            "username": "<username>",
            "validate_certs": true
        }
    },
    "meta": {}
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

@Akasurde One question it's supported the transition change and issue assignation together?
I'm asking because when I add the username _assignee: "ansibleaut"_  or the display name of the user  _assignee: "Ansible Automation"_  it generates the following error:

`    "msg": "[u'Can not deserialize instance of java.util.ArrayList out of START_OBJECT token\\n at [Source: org.apache.catalina.connector.CoyoteInputStream@1768ac96; line: 1, column: 41] (through reference chain: com.atlassian.jira.rest.v2.issue.IssueUpdateBean[\"update\"])']"
`

**Comment by Akasurde** [comment]
Yes I can reproduce this - 

```
TASK [Transit an issue] ***********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "['Can not deserialize instance of java.util.ArrayList out of START_OBJECT token\\n at [Source: org.apache.catalina.connector.CoyoteInputStream@f6f7abc; line: 1, column: 41] (through reference chain: com.atlassian.jira.rest.v2.issue.IssueUpdateBean[\"update\"])']"}
```
It seems that we are not sending the correct JSON that JIRA is expecting.

Let me check and get back to you.

**Comment by Akasurde** [comment]
From this page https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-transitions-post it seems providing assignee is valid.

**Comment by Akasurde** [comment]
@dark-vex Could you please apply this patch and let me know - 

```diff
diff --git a/plugins/modules/web_infrastructure/jira.py b/plugins/modules/web_infrastructure/jira.py
index d10be9eafc..ce3991ed95 100644
--- a/plugins/modules/web_infrastructure/jira.py
+++ b/plugins/modules/web_infrastructure/jira.py
@@ -444,6 +444,13 @@ def transition(restbase, user, passwd, params):
     url = restbase + '/issue/' + params['issue'] + "/transitions"
     data = {'transition': {"id": tid},
             'update': params['fields']}
+    if params['assignee']:
+        params['fields']['assignee'] = {'name': params['assignee']}
+        data.update(params['fields'])
+        # While updating assignee is not part of 'update' key
+        # to avoid raising exception delete this assignee value
+        # https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-transitions-post
+        del data['update']['assignee']

     return True, post(url, user, passwd, params['timeout'], data)
```

I am able to update `assignee` with transition status.

**Comment by dark-vex** [comment]
@Akasurde thanks! I've tried the patch, the error disappear, the transition is applied but the jira task/issue then remain not assigned

```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "assignee": "ansibleaut",
            "comment": null,
            "description": null,
            "fields": {},
            "inwardissue": null,
            "issue": "AUT-30",
            "issuetype": null,
            "jql": null,
            "linktype": null,
            "maxresults": null,
            "operation": "transition",
            "outwardissue": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "project": null,
            "status": "Start Progress",
            "summary": null,
            "timeout": 10.0,
            "uri": "https://<my-jira>.atlassian.net",
            "username": "<user>",
            "validate_certs": true
        }
    },
    "meta": {}
}
META: ran handlers
META: ran handlers
META: ran handlers

PLAY RECAP **************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

![Snap 2021-01-07 at 17 47 15](https://user-images.githubusercontent.com/2905124/103919871-dc2a0500-5110-11eb-93e8-a3a1d86a718e.png)

**Comment by Akasurde** [comment]
@dark-vex I think this is a permission issue. Reassigning an issue requires the following permission

<img width="1196" alt="Screenshot 2021-01-08 at 11 10 57" src="https://user-images.githubusercontent.com/633765/103978775-46d75100-51a2-11eb-8b8c-23e9e18a518b.png">

I have `Free` instance so can't modify the permissions.

I get following error - 

```
{"errorMessages":[],"errors":{"assignee":"Field 'assignee' cannot be set. It is not on the appropriate screen, or unknown."}}
```

**Comment by russoz** [comment]
@dark-vex @Akasurde This can also be the configuration of the specific transition in the workflow. If that transition does not have an associated screen, or if the the screen does not contain the ``assignee`` field, JIRA will diligently block the update - even though we're doing this via API.

**Comment by Akasurde** [comment]
@russoz OK. Thanks. So do you think [the above](https://github.com/ansible-collections/community.general/issues/818#issuecomment-756199132) is OK? Let me know.

**Comment by russoz** [comment]
Sorry, but I don't think it is.

To begin with, the [docs link](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-transitions-post) you mentioned refers to JIRA API v3, whilst our ``jira`` module in Ansible uses JIRA API v2. The link for that should be https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-transitions-post (TBH I have not compared the two docs, so they might tell the exact same story - they look very similar).

The key thing, I believe, it the difference between ``fields`` and ``update`` in JIRA API, and frankly I don't claim to understand it thoroughly:
> fields
> object
>
> List of issue screen fields to update, specifying the sub-field to update and its value for each field. This field provides a straightforward option when setting a sub-field. When multiple sub-fields or other operations are required, use update. Fields included in here cannot be included in update.

> update
> object
>
> List of operations to perform on issue screen fields. Note that fields included in here cannot be included in fields.

In the example, even the structures are distinct:
```
  "update": {
    "comment": [
      {
        "add": {
          "body": "Bug has been fixed."
        }
      }
    ]
  },
  "fields": {
    "assignee": {
      "name": "Will"
    },
    "resolution": {
      "name": "Fixed"
    }
  },
```

>          data = {'transition': {"id": tid},
>                  'update': params['fields']}
>     +    if params['assignee']:
>     +        params['fields']['assignee'] = {'name': params['assignee']}
This is redundant per: https://github.com/ansible-collections/community.general/blob/main/plugins/modules/web_infrastructure/jira.py#L507-L508

>     +        data.update(params['fields'])
The API expects something like (in YAML out of sheer laziness):
```yaml
data:
  transition:
    id: <number>  # or name: <name>
  fields:
    summary: <something>
    assignee: <someone>
    # etc
  update:
    comment:
    - add:
        body: some comment to the ticket
```

And with that you are providing something like:
```yaml
data:
  transition:
    id: <number>  # or name: <name>
  summary: <something>
  assignee: <someone>
  # etc

  # As data['update'] is not touched by your patch, 
  # it still provides the necessary information 
  # (except for the assignee, per your deletion below)
  update:   
    comment:
    - add:
        body: some comment to the ticket
  fields:
    assignee: <user>
```

>     +        del data['update']['assignee']
Since you added it to ``fields`` we cannot have it in ``update``, as described in the API docs.

> I am able to update `assignee` with transition status.
Yes, but the underlying problem is still there.

It feels like the ``assignee`` thing is just the tip of an iceberg here.

And then, there is the fact that Atlassian is deprecating using ``{ 'name': <user> }`` for user fields, as described in:
* https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-assignee-put
* https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/

**Comment by russoz** [comment]
I don't have a JIRA instance I can play with for this issue. 

@dark-vex  @Akasurde could you guys change the same thing but instead of changing the assignee, change the summary. I reckon we should bump into the same problems.

**Comment by dark-vex** [comment]
@russoz yes, sure. I've tried with this:
```
  tasks:
    - name: Change summary and transition
      community.general.jira:
        uri: '{{ jira_server }}'
        username: '{{ jira_user }}'
        password: '{{ jira_pass }}'
        issue: '{{ issue_id }}'
        operation: transition
        summary: 'Test issue 818'
        status: 'Start Progress'
```

The transition change but not the summary:
```
daniele@daniele-PC:~/ansible-jira$ ansible-playbook jira.yml -e issue_id=AUT-30 -vvv
ansible-playbook 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/daniele/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/daniele/.local/lib/python3.7/site-packages/ansible
  executable location = /home/daniele/.local/bin/ansible-playbook
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: jira.yml ******************************************************************************************************************************************************************************************************************
1 plays in jira.yml

PLAY [Test Read/Write Jira] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************
task path: /home/daniele/ansible-jira/jira.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: daniele
<127.0.0.1> EXEC /bin/sh -c 'echo ~daniele && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/daniele/.ansible/tmp `"&& mkdir "` echo /home/daniele/.ansible/tmp/ansible-tmp-1610286429.7132652-827-29278454699981 `" && echo ansible-tmp-1610286429.7132652-827-29278454699981="` echo /home/daniele/.ansible/tmp/ansible-tmp-1610286429.7132652-827-29278454699981 `" ) && sleep 0'
Using module file /home/daniele/.local/lib/python3.7/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/daniele/.ansible/tmp/ansible-local-821e834008r/tmptjy197da TO /home/daniele/.ansible/tmp/ansible-tmp-1610286429.7132652-827-29278454699981/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/daniele/.ansible/tmp/ansible-tmp-1610286429.7132652-827-29278454699981/ /home/daniele/.ansible/tmp/ansible-tmp-1610286429.7132652-827-29278454699981/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/daniele/.ansible/tmp/ansible-tmp-1610286429.7132652-827-29278454699981/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/daniele/.ansible/tmp/ansible-tmp-1610286429.7132652-827-29278454699981/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [Assign an issue and change status] ********************************************************************************************************************************************************************************************
task path: /home/daniele/ansible-jira/jira.yml:12
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: daniele
<127.0.0.1> EXEC /bin/sh -c 'echo ~daniele && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/daniele/.ansible/tmp `"&& mkdir "` echo /home/daniele/.ansible/tmp/ansible-tmp-1610286432.9190354-917-249816310089110 `" && echo ansible-tmp-1610286432.9190354-917-249816310089110="` echo /home/daniele/.ansible/tmp/ansible-tmp-1610286432.9190354-917-249816310089110 `" ) && sleep 0'
Using module file /home/daniele/.local/lib/python3.7/site-packages/ansible_collections/community/general/plugins/modules/jira.py
<127.0.0.1> PUT /home/daniele/.ansible/tmp/ansible-local-821e834008r/tmp3fxcg97e TO /home/daniele/.ansible/tmp/ansible-tmp-1610286432.9190354-917-249816310089110/AnsiballZ_jira.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/daniele/.ansible/tmp/ansible-tmp-1610286432.9190354-917-249816310089110/ /home/daniele/.ansible/tmp/ansible-tmp-1610286432.9190354-917-249816310089110/AnsiballZ_jira.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/daniele/.ansible/tmp/ansible-tmp-1610286432.9190354-917-249816310089110/AnsiballZ_jira.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/daniele/.ansible/tmp/ansible-tmp-1610286432.9190354-917-249816310089110/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "assignee": null,
            "comment": null,
            "description": null,
            "fields": {},
            "inwardissue": null,
            "issue": "AUT-30",
            "issuetype": null,
            "jql": null,
            "linktype": null,
            "maxresults": null,
            "operation": "transition",
            "outwardissue": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "project": null,
            "status": "Start Progress",
            "summary": "Test issue 818",
            "timeout": 10.0,
            "uri": "https://<my-jira>.atlassian.net",
            "username": "<user>",
            "validate_certs": true
        }
    },
    "meta": {}
}
META: ran handlers
META: ran handlers
META: ran handlers

PLAY RECAP **************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

![Snap 2021-01-10 at 14 53 52](https://user-images.githubusercontent.com/2905124/104124902-b6d90900-5353-11eb-8639-46db7f2bf1ae.png)

**Comment by russoz** [comment]
@dark-vex those are the result _with_ the patch, right?

**Comment by dark-vex** [comment]
@russoz I confirm that the result above is **with** the patch applied

**Comment by russoz** [comment]
@dark-vex those alright, as far as I can tell, it confirms what I thought it was the problem: using ``{ "data": { "update": ... }}`` for the fields does not work, we should be using ``{ "data": { "fields": ... }}`` instead. Or, IMHO, we should be using ``python-jira`` instead of having to worry about this type of things at the ansible module level.

I suspect that if we simply change it to ``fields`` something else will stop working - it must have worked for _some_ case, and the example from Atlassian's documentation clearly shows how it is used for comments.

I wasn't planning on working on this, but if no one takes on it, I suppose I can come up with a PR next week or so. On the other hand, I would be more than happy to review any PR submitted for it.

**Comment by russoz** [comment]
@dark-vex Sorry for the delay. I have re-read the issue here and I still think my last statement is correct. But I am not setting up a JIRA instance just to try it, so I haven't properly tested my hypothesis. That said, I have just raised the PR #1978 , would you please test if it solves the problem? TIA

**Comment by dark-vex** [comment]
Hey @russoz no worries at all :-) I have tried the patch in the PR #1978 but unfortunately it doesn't seem to be working

Task:
```
  tasks:
    - name: Comment an issue and change status
      community.general.jira:
        uri: '{{ jira_server }}'
        username: '{{ jira_user }}'
        password: '{{ jira_pass }}'
        issue: '{{ issue_id }}'
        operation: transition
        summary: 'Test issue 818'
        comment: 'Test PR #1978'
        status: 'Start Progress'
```

Task output:
```TASK [Comment an issue and change status] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/daniele/ansible-abuseipdb/jira.yml:12
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: daniele
<127.0.0.1> EXEC /bin/sh -c 'echo ~daniele && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/daniele/.ansible/tmp `"&& mkdir "` echo /home/daniele/.ansible/tmp/ansible-tmp-1615117374.1651661-2131-142996502780202 `" && echo ansible-tmp-1615117374.1651661-2131-142996502780202="` echo /home/daniele/.ansible/tmp/ansible-tmp-1615117374.1651661-2131-142996502780202 `" ) && sleep 0'
Using module file /home/daniele/.local/lib/python3.7/site-packages/ansible_collections/community/general/plugins/modules/jira.py
<127.0.0.1> PUT /home/daniele/.ansible/tmp/ansible-local-2041h94mopxz/tmpph1kbsdk TO /home/daniele/.ansible/tmp/ansible-tmp-1615117374.1651661-2131-142996502780202/AnsiballZ_jira.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/daniele/.ansible/tmp/ansible-tmp-1615117374.1651661-2131-142996502780202/ /home/daniele/.ansible/tmp/ansible-tmp-1615117374.1651661-2131-142996502780202/AnsiballZ_jira.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/daniele/.ansible/tmp/ansible-tmp-1615117374.1651661-2131-142996502780202/AnsiballZ_jira.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/daniele/.ansible/tmp/ansible-tmp-1615117374.1651661-2131-142996502780202/ > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "assignee": null,
            "comment": "Test PR #1978",
            "description": null,
            "fields": {},
            "inwardissue": null,
            "issue": "AUT-29",
            "issuetype": null,
            "jql": null,
            "linktype": null,
            "maxresults": null,
            "operation": "transition",
            "outwardissue": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "project": null,
            "status": "Start Progress",
            "summary": "Test issue 818",
            "timeout": 10.0,
            "uri": "https://<my-jira>.atlassian.net",
            "username": "<user>",
            "validate_certs": true
        }
    },
    "meta": {}
}
META: ran handlers
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

![jira-git-issue-818](https://user-images.githubusercontent.com/2905124/110239035-28dd6100-7f45-11eb-9220-00791c2de4bd.JPG)

**Comment by russoz** [comment]
@dark-vex I would suggest trying with one field at a time. Try `summary` only, then `comment`, `assignee` individually. Another thing to consider is: log into the JIRA instance via browser and perform that same transition manually: look which fields are available in the transition screen, and try those via the ansible module (I'd try each individually first, and if that works, then try bundling them up). If there is no screen for the transition, that itself could be the problem becasue, AFAIR jira won't allow us to update fields that are not in the transition screen.

**Comment by dark-vex** [comment]
@russoz I've tried with one field per time and I've tried with two transitions. I think you're right about the transition screen, see my tests below

With the "Start Progress" transition (which doesn't have a screen):
- Tried with just Summary and is not updated
- Tried with just comment and is not updated
- With assignee is giving the error 'Field assignee cannot be set' (tried with both the user display name and username)

With the "Stop Progress" transition which _does have_ a screen for transition (fields available: Resolution, Linked Issues, Issue, Comment):
- Tried with just Summary and is not updated
- Tried with just comment the comment is added (due the nature of the fix in the PR of course the comment is replaced with the text "Bug has been fixed.")
- With assignee is giving the error 'Field assignee cannot be set' (tried with both the user display name and username)

**Comment by russoz** [comment]
@dark-vex I can think of a couple of other tests we could do there (if you are willing to):
1. Adding the assignee to the transition screen and checking whether it works (I would expect it to) and
2. Running all these tests against the current codebase instead of the PR code - I would expect the comment to fail and the assignee (as suggested in the previous item in this comment) to fail as well.

If those tests play out as expected, I think we can move forward with that PR, but we need to ensure users know that the ansible playbook is half of it, they also need to configure their jira instances' transition screens for it to work.

**Comment by dark-vex** [comment]
Apologies for delay (busy week), yes sure, I will try these other tests over the weekend and let you know :-)

**Comment by russoz** [comment]
No apologies needed, thank you for your time on this :-)

**Comment by SamKirsch10** [comment]
@russoz - Just tested your patch on our process, and our tickets are now transitioning! :) Can't wait till it's in an we will pull from master

**Comment by russoz** [comment]
@dark-vex please let us know if there's any update on this. If you cannot test this any time soon, we might as well merge the PR on @SamKirsch10 test.

**Comment by dark-vex** [comment]
@russoz I had time to try with codebase. I've added assignee, description and summary to the 'Start Progress' transition screen

<img width="809" alt="Screenshot 2021-03-19 at 09 57 32" src="https://user-images.githubusercontent.com/2905124/111755875-df243d00-8899-11eb-9cd6-7a568e95cabb.png">

```
  tasks:
    - name: Comment an issue and change status
      community.general.jira:
        uri: '{{ jira_server }}'
        username: '{{ jira_user }}'
        password: '{{ jira_pass }}'
        issue: '{{ issue_id }}'
        operation: transition
        summary: 'Test issue 818'
        comment: 'Test with codebase'
        description: 'Test Description'
        status: 'Start Progress'
```
The task is executed and says "changed" but as we expected no changes gets applied. To the above task if I add the assignee field either with the displayed name or username the task fail with the following:
```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "assignee": "ansibleaut", 
            "comment": "Test with codebase", 
            "description": "Test Description", 
            "fields": {
                "assignee": {
                    "name": "ansibleaut"
                }
            }, 
            "inwardissue": null, 
            "issue": "AUT-29", 
            "issuetype": null, 
            "jql": null, 
            "linktype": null, 
            "maxresults": null, 
            "operation": "transition", 
            "outwardissue": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "project": null, 
            "status": "Start Progress", 
            "summary": "Test issue 818", 
            "timeout": 10.0, 
            "uri": "https://<my-jira>.atlassian.net",
            "username": "<user>",
            "validate_certs": true
        }
    }, 
    "msg": "[u'Can not deserialize instance of java.util.ArrayList out of START_OBJECT token\\n at [Source: org.apache.catalina.connector.CoyoteInputStream@4c64bdba; line: 1, column: 41] (through reference chain: com.atlassian.jira.rest.v2.issue.IssueUpdateBean[\"update\"])']"
}
```
I will follow up with the same tests with the PR ASAP

**Comment by dark-vex** [comment]
Tried also with the PR, this is the task:
```
  tasks:
    - name: Assign an issue and change status
      community.general.jira:
        uri: '{{ jira_server }}'
        username: '{{ jira_user }}'
        password: '{{ jira_pass }}'
        issue: '{{ issue_id }}'
        operation: transition
        assignee: 'Ansible Automation'
        summary: 'Test issue 818'
        comment: 'Test with PR'
        description: 'Test Description'
        status: 'Start Progress'
```

The task is executed and says "changed" but only the comment "Bug has been fixed." gets applied. This the task output:
```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "assignee": "Ansible Automation",
            "comment": "Test with PR",
            "description": "Test Description",
            "fields": {
                "assignee": {
                    "name": "Ansible Automation"
                }
            },
            "inwardissue": null,
            "issue": "AUT-29",
            "issuetype": null,
            "jql": null,
            "linktype": null,
            "maxresults": null,
            "operation": "transition",
            "outwardissue": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "project": null,
            "status": "Start Progress",
            "summary": "Test issue 818",
            "timeout": 10.0,
            "uri": "https://<my-jira>.atlassian.net",
            "username": "<user>",
            "validate_certs": true
        }
    },
    "meta": {}
}
META: ran handlers
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

![Cattura](https://user-images.githubusercontent.com/2905124/111880837-feac8a00-89ad-11eb-9cea-0aab85f5a8d4.JPG)

**Comment by russoz** [comment]
hi @dark-vex , thanks for the tests, I found two issues:
- we were updating the `fields` dict with the `summary` but
  - not the description
  - we were adding `params['fields']` (raw) to the payload instead of the adjust `fields`

I have just fixed that, it should improve the outcome of our tests.

**Comment by dark-vex** [comment]
Thanks @russoz , I've tried with the new modifications made in the PR but I still getting only the comment working
```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "assignee": "Ansible Automation",
            "comment": "Test with PR",
            "description": "Test Description",
            "fields": {
                "assignee": {
                    "name": "Ansible Automation"
                }
            },
            "inwardissue": null,
            "issue": "AUT-29",
            "issuetype": null,
            "jql": null,
            "linktype": null,
            "maxresults": null,
            "operation": "transition",
            "outwardissue": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "project": null,
            "status": "Start Progress",
            "summary": "Test issue 818",
            "timeout": 10.0,
            "uri": "https://<my-jira>.atlassian.net",
            "username": "<user>",
            "validate_certs": true
        }
    },
    "meta": {}
}
META: ran handlers
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

![Cattura](https://user-images.githubusercontent.com/2905124/111911370-a0db7900-8a65-11eb-9ff3-3fef12a8afd5.JPG)

This is how I've applied the patch to /ansible_collections/community/general/plugins/modules/jira.py file I think I didn't forgot anything but let's double-check :-) 
```
def transition(restbase, user, passwd, params):
    # Find the transition id
    turl = restbase + '/issue/' + params['issue'] + "/transitions"
    tmeta = get(turl, user, passwd, params['timeout'])

    target = params['status']
    tid = None
    for t in tmeta['transitions']:
        if t['name'] == target:
            tid = t['id']
            break

    if not tid:
        raise ValueError("Failed find valid transition for '%s'" % target)

    # Temp patch https://github.com/ansible-collections/community.general/pull/1978/files
    fields = dict(params['fields'])
    if params['summary'] is not None:
        fields.update({'summary': params['summary']})
    if params['description'] is not None:
        fields.update({'description': params['description']})
    # End patch
    # Perform it
    url = restbase + '/issue/' + params['issue'] + "/transitions"
    data = {'transition': {"id": tid},
    #        'update': params['fields']}
    # Temp patch https://github.com/ansible-collections/community.general/pull/1978/files
            'fields': params['fields']}
    if params['comment'] is not None:
        data.update({"update": {
            "comment": [{
                "add": {"body": params['comment']}
            }],
        }})
    # End temp patch
    ret = post(url, user, passwd, params['timeout'], data)

    return ret
```

**Comment by SamKirsch10** [comment]
@dark-vex - You have a comment that's blocking the update on the fields param.
```
data = {'transition': {"id": tid},
    #        'update': params['fields']}
```
Remove that and retest

**Comment by SamKirsch10** [comment]
Working through some tests myself, while the transition piece works, @dark-vex is correct that comments / description updates aren't. I've made some changes to the transition function that _**should**_ help. Let me know @dark-vex 

```
def transition(restbase, user, passwd, params):
    # Find the transition id
    turl = restbase + '/issue/' + params['issue'] + "/transitions"
    tmeta = get(turl, user, passwd, params['timeout'])

    target = params['status']
    tid = None
    for t in tmeta['transitions']:
        if t['name'] == target:
            tid = t['id']
            break

    if not tid:
        raise ValueError("Failed find valid transition for '%s'" % target)
    if 'fields' not in params:
        params['fields'] = dict()
    if params['summary'] is not None:
        params['fields'].update({'summary': params['summary']})
    if params['description'] is not None:
        params['fields'].update({'description': params['description']})
    if 'fields' in params:
        edit(restbase, user, passwd, params)
    if params['comment'] is not None:
        comment(restbase, user, passwd, params)
    # Perform it
    url = restbase + '/issue/' + params['issue'] + "/transitions"
    data = {'transition': {"id": tid}}

    return True, post(url, user, passwd, params['timeout'], data)
```

@russoz - would you like me to PR these changes post- @dark-vex confirming the fix?

**Comment by russoz** [comment]
@SamKirsch10 although it works, in the sense that it get the values changed, this woud make three API requests to JIRA, when it should work in only one.

**Comment by SamKirsch10** [comment]
@russoz - The reasoning behind that is, the ability to edit pieces during a transition depends **heavily** on if they're allowed/enabled in the jira transition settings. From my research in the API, if the jira target server doesn't have a setting somewhere, some edits during the transition API call won't work. 

With separate API calls, the end result is the same, but I understand the "ugliness" with additional API calls

**Comment by russoz** [comment]
> @russoz - The reasoning behind that is, the ability to edit pieces during a transition depends **heavily** on if they're allowed/enabled in the jira transition settings. From my research in the API, if the jira target server doesn't have a setting somewhere, some edits during the transition API call won't work.

That's exactly right and, on many occasions, on purpose. A JIRA admin might want to allow changes in the fields during the transition only, but not afterwards (I know I did that more than once when I was the maintainer of the jira for the company I worked for 5 years ago). 

Not only that might be a problem in such scenarios, but there is also the question of idempotency and error-handling. With 3 API calls, what should we do if the second request fails? What if only the third one? We would have fields and comments updated, but no transition. To rollback the first requests we would have to place yet more API requests.

I understand it is a PITA but I still believe we should pursue the one request solution. If I can make some time for that, I am thinking of spinning one of those free instances with Atlassian so I can test this.

**Comment by felixfontein** [comment]
How about having a setting which allows to enable to split up everything into multiple requests (default off), with a warning what errors could result in partial changes that will not be rolled back? Not sure how much work that will be to implement :)

**Comment by russoz** [comment]
Hi @SamKirsch10 , @dark-vex , @felixfontein 

Sorry for the delay. I have been running some tests here, and the problem with the `assignee` is slightly more complicated than meets the eye. In 2018 Atlassian decided to let go `username` in Jira (and Confluence for that matter). Now the **only** thing that can be used to identify an user is the `accountId` which is akin to an UUID for the user. And as far as I can tell, there is no way to *translate* user names into these account Ids - there is no longer an *user name* whatsoever. That happens today in the JIRA Cloud service.

So, I have added a new parameter `accountId` to be used in these cases - "older" JIRA users will be able to continue using `assignee` while the new ones can use `accountId`. The problem of locating these `accountId` values previously still remains, but that is going to be true regardless of the JIRA client being used. I reckon that should be handled in a different issue.

So, I created a brand new free JIRA instance in atlassian.net, created a project using the "classic" workflow. The `Resolve Screen` was modified to contain the `Description` field. With that setup, I was able to make this playbook below to work:
```yaml
---
- name: jira play
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - community.general.jira:
      uri: "{{ uri }}"
      username: "{{ user }}"
      password: "{{ pasw }}"
      project: "{{ proj }}"
      operation: create
      summary: test ticket
      description: bla bla bla
      issuetype: Task
    register: issue

  - debug:
      msg: Issue={{ issue }}
  - name: Add comment bleep bleep
    community.general.jira:
      uri: "{{ uri }}"
      username: "{{ user }}"
      password: "{{ pasw }}"
      issue: "{{ issue.meta.key }}"
      operation: comment
      comment: bleep bleep!
  - name: Transition -> In Progress with comment
    community.general.jira:
      uri: "{{ uri }}"
      username: "{{ user }}"
      password: "{{ pasw }}"
      issue: "{{ issue.meta.key }}"
      operation: transition
      status: Start Progress
      comment: -> in progress => this comment is lost because there is no screen in that transition
  - name: Change assignee
    community.general.jira:
      uri: "{{ uri }}"
      username: "{{ user }}"
      password: "{{ pasw }}"
      issue: "{{ issue.meta.key }}"
      operation: edit
      accountId: "{{ user2 }}"
  - name: Transition -> Resolved with comment
    community.general.jira:
      uri: "{{ uri }}"
      username: "{{ user }}"
      password: "{{ pasw }}"
      issue: "{{ issue.meta.key }}"
      operation: transition
      status: Resolve Issue
      comment: -> resolved
      accountId: "{{ user1 }}"
      fields:
        resolution:
          name: Done
        description: wakawakawakawaka

  - debug:
      msg:
        - Issue = {{ issue.meta.key }}
        - URL = {{ issue.meta.self }}
```

**Comment by russoz** [comment]
![image](https://user-images.githubusercontent.com/103110/113508943-fb68ef00-95a6-11eb-996e-e384706d864f.png)

**Comment by russoz** [comment]
I will later add this as an `unsupported` integration test, because obviously we won't be able to run it from the CI.

**Comment by russoz** [comment]
err... I actually added the integration test already.
